name: debug_console
description: A new Flutter package project.
version: 0.0.1
homepage: https://github.com/DrafaKiller/DebugConsole-flutter

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  expandable: ^5.0.1
  flutter:
    sdk: flutter
  rxdart: ^0.27.4
  shake: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0